baseURL = "https://nitschinger.at/"
languageCode = "en-us"
title = "daschl writes. sometimes."
author = "Michael Nitschinger"
theme = "hugo-natrium-theme"
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
pygmentsOptions = "linenos=table"
disablePathToLower = true
disqusShortname = "daschl"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 10

[[menu.main]]
    name = "-> twitter"
    url = "https://twitter.com/daschl"
    weight = 30

[[menu.main]]
    name = "-> github"
    url = "https://github.com/daschl"
    weight = 40

[[menu.main]]
    name = "imprint"
    url = "/imprint/"
    weight = 20

[params]