baseURL = "https://nitschinger.at/"
languageCode = "en-us"
title = "daschl writes. sometimes."
author = "Michael Nitschinger"
theme = "hugo-natrium-theme"
rssLimit = 10
paginate = 10
disablePathToLower = true
disqusShortname = "daschl"
googleAnalytics = "UA-19686689-1"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 10

[[menu.main]]
    name = "-> twitter"
    url = "https://twitter.com/daschl"
    weight = 30

[[menu.main]]
    name = "-> github"
    url = "https://github.com/daschl"
    weight = 40

[[menu.main]]
    name = "imprint"
    url = "/imprint/"
    weight = 20

[params]