baseurl = "https://nitschinger.at"
languageCode = "en-us"
title = "daschl writes. sometimes."
author = "Michael Nitschinger"
theme = "purehugo"
disqusShortname = "daschl"
twitterName = "daschl"
githubName = "daschl"
disablePathToLower = true
pygmentsCodeFences = true
pygmentsStyle = "xcode"
pygmentsOptions = "linenos=table"